deploy:
  rocketeer:
    image: fdplugins/ssh-php
    when:
      branch: develop
    commands:
      - ping 10.0.1.55
      - php rocketeer.phar deploy --stage=staging --no-interaction
  rocketeer:
    image: fdplugins/ssh-php
    when:
      branch: master
    commands:
      - php rocketeer.phar deploy --stage=production --branch=master --no-interaction