deploy:
  rocketeer:
    image: fdplugins/ssh-php
    when:
      branch: develop
    commands:
      - cat ~/.ssh/id_rsa.pub
      - cat /root/.ssh/id_rsa.pub
      - php rocketeer.phar deploy --stage=staging --no-interaction
  rocketeer:
    image: fdplugins/ssh-php
    when:
      branch: master
    commands:
      - php rocketeer.phar deploy --stage=production --branch=master --no-interaction